### ISSUE TITLE
Milestone1 feedback

### ISSUE THREAD

**Issue by ArmaghanSarvar** [UBC-MDS/dragracerviz#14]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

Section 1: Motivation and purpose: writing: 2/2, reasoning: 6/8
- More details can be provided on what the application visualizations will show instead of a high-level explanation of the drag race and how exactly the solutions help with the problems of the specified audience.

Section 2: Description of data: writing: 2/2, reasoning: 5/8
- Although the variables have been explained, evident exploratory data analysis is not added (for example how many null/missing values does each variable have?)
- Where does the dataset come from? Better to cite the main resource of the dataset and not only mention the package that provides it.

Section 3: Research questions and usage scenarios: writing: 2/2, reasoning: 8/12
- Unfortunately, only a brief explanation of what the app is going to display has been added and it would have been more helpful if the team had provided a higher level of detail.

Section 4: Description of the app and sketch: viz: 10/10, writing: 2/2, reasoning: 3/3

Section 5: Teamwork contract and collaborative documentation: reasoning: 4/4

Section 6: Code of conduct: 1/1

Section 7: Contribution guidelines: 1/1

If anything is unclear, please feel free to ask questions. Great work!

**Comment by marianagyby** [comment]
Hi @ArmaghanSarvar,

Regarding the comment in Section 2 (description of the data) for the EDA not being added, the milestone instructions indicated that EDA is not required. Here is the link to the milestone instructions we were given: ["We will not be grading the EDA aspect..."](https://pages.github.ubc.ca/MDS-2022-23/DSCI_532_viz-2_students/materials/assignments/milestone1.html#section-2-description-of-the-data). 

Thank you for your feedback!
